---

- hosts: all
  become: true
  tasks:

  - name: install neovim and tmux 
    apt:
      name: 
        - "{{ neovim_package }}" 
        - "{{ tmux_package }}" 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
