---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: general,update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: main
  become: true
  tasks:

  - name: install neovim and tmux 
    tags: neovim,tmux
    package:
      name: 
        - neovim
        - tmux
      state: latest
