---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always,updates 
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: main
  become: true
  tasks:

  - name: install gcc and tmux 
    tags: gcc,tmux,ubuntu
    apt:
      name: 
        - gcc 
        - tmux
      state: latest
    when: ansible_distribution == "Ubuntu"
