---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always,updates 
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add simone user 
    tags: always
    user:
      name: simone
      group: root

- hosts: main
  become: true
  tasks:

  - name: install gcc and tmux 
    tags: gcc,tmux,ubuntu
    apt:
      name: 
        - gcc 
        - tmux
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default tmux config
    tags: tmux,config
    copy:
      src: default_tmux_config.conf
      dest: /home/erik/.tmux.conf
      owner: erik
      group: erik
      mode: 0644
