---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install neovim and tmux 
    package:
      name: 
        - neovim
        - tmux
      state: latest
      update_cache: yes
