- name: install gcc and tmux 
  tags: gcc,tmux,ubuntu
  package:
    name: 
      - "{{ tmux_package_name }}" 
      - "{{ gcc_package_name }}" 
    state: latest

- name: copy default tmux config
  tags: tmux,config
  copy:
    src: default_tmux_config.conf
    dest: /home/erik/.tmux.conf
    owner: erik
    group: erik
    mode: 0644
